name: LLM RAG

queries:
- content: LLMs in Medicine
  max_results: 5
- content: retrieval in Large Language Models
  max_results: 5

questions:
- content: "What retrieval methods are used in this paper?"
- content: "Does the retrieval method involve traditional IR techniques?"
- content: "What scenarios are the retrieval methods used in?"