name: LLM RAG

queries:
- content: RAG in LLMs
  max_results: 10
- content: retrieval in Large Language Models
  max_results: 10

questions:
- content: "What retrieval methods are used in this paper?"
- content: "Does the retrieval method involve traditional IR techniques?"
- content: "What scenarios are the retrieval methods used in?"